import { dummyProduct } from "../assets/assets";

export const ProductItems = [
  {
    title: "12V Lithium Battery",
    productType: "Battery",
    description: "High-performance 12V rechargeable lithium battery for solar and backup systems.",
    price: 119.99,
    icon: dummyProduct,
    saleCount: 1020,
    remainingStock: 300,
  },
  {
    title: "Portable Power Bank 20000mAh",
    productType: "Power Bank",
    description: "Fast-charging dual-output power bank with LED display and USB-C input.",
    price: 45.0,
    icon: dummyProduct,
    saleCount: 980,
    remainingStock: 620,
  },
  {
    title: "AA Rechargeable Batteries (4-Pack)",
    productType: "Battery",
    description: "Eco-friendly and long-lasting AA batteries for household electronics.",
    price: 15.5,
    icon: dummyProduct,
    saleCount: 1500,
    remainingStock: 450,
  },
  {
    title: "Solar Battery Charger",
    productType: "Charger",
    description: "Compact solar charger ideal for charging phones and batteries on the go.",
    price: 69.99,
    icon: dummyProduct,
    saleCount: 860,
    remainingStock: 200,
  },
  {
    title: "9V Alkaline Battery",
    productType: "Battery",
    description: "Reliable 9V battery for smoke detectors, toys, and remote controls.",
    price: 5.75,
    icon: dummyProduct,
    saleCount: 1320,
    remainingStock: 980,
  },
  {
    title: "Laptop Battery for Dell XPS",
    productType: "Laptop Battery",
    description: "High-capacity replacement battery compatible with Dell XPS models.",
    price: 89.99,
    icon: dummyProduct,
    saleCount: 300,
    remainingStock: 75,
  },
  {
    title: "Camera Battery for Canon EOS",
    productType: "Camera Battery",
    description: "Rechargeable battery compatible with Canon EOS series cameras.",
    price: 39.0,
    icon: dummyProduct,
    saleCount: 1100,
    remainingStock: 340,
  },
  {
    title: "18650 Lithium Cell (2-Pack)",
    productType: "Battery",
    description: "High-drain 18650 rechargeable cells ideal for flashlights and e-bikes.",
    price: 24.99,
    icon: dummyProduct,
    saleCount: 790,
    remainingStock: 150,
  },
  {
    title: "Battery Tester & Analyzer",
    productType: "Accessory",
    description: "Portable digital tester for AA, AAA, C, D, and 9V batteries.",
    price: 19.5,
    icon: dummyProduct,
    saleCount: 670,
    remainingStock: 270,
  },
  {
    title: "iPhone 13 Replacement Battery",
    productType: "Mobile Battery",
    description: "Original quality lithium-ion replacement battery for iPhone 13.",
    price: 59.9,
    icon: dummyProduct,
    saleCount: 1200,
    remainingStock: 150,
  },

  // 30 more products (continued)
  {
    title: "Battery Pack for Xbox Controller",
    productType: "Gaming Accessory",
    description: "Rechargeable battery pack with USB charging cable for Xbox controllers.",
    price: 29.99,
    icon: dummyProduct,
    saleCount: 700,
    remainingStock: 390,
  },
  {
    title: "CR2032 Coin Cell Battery (5-Pack)",
    productType: "Battery",
    description: "Button cell batteries for watches, remotes, and medical devices.",
    price: 8.99,
    icon: dummyProduct,
    saleCount: 2500,
    remainingStock: 1300,
  },
  {
    title: "Smartphone Fast Charger 30W",
    productType: "Charger",
    description: "USB-C PD charger compatible with Android and iOS devices.",
    price: 25.99,
    icon: dummyProduct,
    saleCount: 1400,
    remainingStock: 490,
  },
  {
    title: "NiMH AAA Rechargeable Batteries",
    productType: "Battery",
    description: "Low self-discharge AAA batteries for toys and remotes.",
    price: 12.49,
    icon: dummyProduct,
    saleCount: 990,
    remainingStock: 480,
  },
  {
    title: "MacBook Pro Battery A1582",
    productType: "Laptop Battery",
    description: "OEM replacement battery for MacBook Pro 13-inch Retina.",
    price: 109.0,
    icon: dummyProduct,
    saleCount: 350,
    remainingStock: 80,
  },
  {
    title: "Battery Operated LED Strip",
    productType: "Lighting",
    description: "Flexible, battery-powered RGB LED light strip with remote.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Garden Light Batteries",
    productType: "Battery",
    description: "NiCd batteries suitable for outdoor solar-powered lights.",
    price: 9.99,
    icon: dummyProduct,
    saleCount: 870,
    remainingStock: 320,
  },
  {
    title: "Portable Jump Starter Battery",
    productType: "Car Battery",
    description: "Compact car battery jumper with USB and flashlight functions.",
    price: 129.95,
    icon: dummyProduct,
    saleCount: 540,
    remainingStock: 120,
  },
  {
    title: "D Cell Alkaline Battery (2-Pack)",
    productType: "Battery",
    description: "Durable D-size batteries for lanterns and large flashlights.",
    price: 11.99,
    icon: dummyProduct,
    saleCount: 620,
    remainingStock: 300,
  },
  {
    title: "Bluetooth Battery Monitor",
    productType: "Accessory",
    description: "Smart monitor for checking battery health via mobile app.",
    price: 42.75,
    icon: dummyProduct,
    saleCount: 460,
    remainingStock: 190,
  },
  {
    title: "Universal Laptop Battery Charger",
    productType: "Charger",
    description: "Multi-brand charger compatible with most laptop batteries.",
    price: 59.49,
    icon: dummyProduct,
    saleCount: 430,
    remainingStock: 215,
  },
  {
    title: "Electric Bike Battery 48V",
    productType: "Battery",
    description: "Rechargeable battery pack suitable for 48V electric bikes.",
    price: 279.99,
    icon: dummyProduct,
    saleCount: 120,
    remainingStock: 40,
  },
  {
    title: "GoPro Hero Battery Pack",
    productType: "Camera Battery",
    description: "Rechargeable battery for GoPro Hero 8/9/10 series.",
    price: 34.99,
    icon: dummyProduct,
    saleCount: 710,
    remainingStock: 160,
  },
  {
    title: "Battery Storage Organizer Box",
    productType: "Accessory",
    description: "Holds up to 100 batteries and includes a battery tester.",
    price: 21.0,
    icon: dummyProduct,
    saleCount: 890,
    remainingStock: 500,
  },
  {
    title: "Remote Control Car Battery 7.2V",
    productType: "Battery",
    description: "NiMH battery pack compatible with most RC cars.",
    price: 31.99,
    icon: dummyProduct,
    saleCount: 580,
    remainingStock: 140,
  },
  {
    title: "Solar Panel Battery Controller",
    productType: "Controller",
    description: "Regulates charge from solar panels to battery systems.",
    price: 48.25,
    icon: dummyProduct,
    saleCount: 450,
    remainingStock: 150,
  },
  {
    title: "Wireless Doorbell Battery",
    productType: "Battery",
    description: "Long-life battery for wireless doorbell systems.",
    price: 6.99,
    icon: dummyProduct,
    saleCount: 1050,
    remainingStock: 800,
  },
  {
    title: "Heavy Duty 6V Lantern Battery",
    productType: "Battery",
    description: "Large 6V battery for camping lanterns and emergency lights.",
    price: 14.5,
    icon: dummyProduct,
    saleCount: 310,
    remainingStock: 95,
  },
  {
    title: "Kids Ride-On Car Battery 12V",
    productType: "Battery",
    description: "Lead-acid replacement battery for children's electric cars.",
    price: 49.99,
    icon: dummyProduct,
    saleCount: 370,
    remainingStock: 110,
  },
  {
    title: "UPS Backup Battery 24V",
    productType: "Battery",
    description: "Reliable backup battery for uninterrupted power supplies.",
    price: 145.75,
    icon: dummyProduct,
    saleCount: 230,
    remainingStock: 50,
  },
  {
    title: "Rechargeable Pet Collar Battery",
    productType: "Battery",
    description: "Compact rechargeable battery for LED pet collars.",
    price: 12.0,
    icon: dummyProduct,
    saleCount: 650,
    remainingStock: 210,
  },
  {
    title: "Drone Battery 11.1V",
    productType: "Battery",
    description: "LiPo battery compatible with most consumer drones.",
    price: 64.99,
    icon: dummyProduct,
    saleCount: 275,
    remainingStock: 90,
  },
  {
    title: "Battery Operated LED Strip",
    productType: "Lighting",
    description: "Flexible, battery-powered RGB LED light strip with remote.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Panel",
    productType: "Lighting",
    description: "Solar panel for charging batteries and devices.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Panel",
    productType: "Lighting",
    description: "Solar panel for charging batteries and devices.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Panel",
    productType: "Lighting",
    description: "Solar panel for charging batteries and devices.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Panel",
    productType: "Lighting",
    description: "Solar panel for charging batteries and devices.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Panel",
    productType: "Lighting",
    description: "Solar panel for charging batteries and devices.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
  {
    title: "Solar Panel",
    productType: "Lighting",
    description: "Solar panel for charging batteries and devices.",
    price: 17.99,
    icon: dummyProduct,
    saleCount: 1300,
    remainingStock: 620,
  },
];
