import {
  customerImg1,
  customerImg2,
  customerImg3,
  customerImg4,
  customerImg5,
  customerImg6,
  DummyPro,
} from "../assets/assets";

export const RecentPurchaseItems = [
  {
    orderId: "ORD-00001",
    productName: "Wireless Mouse",
    customerImg: customerImg1,
    date: "2023-10-01",
    customerName: "John Doe",
    customerEmail: "john@example.com",
    customerPhone: "+91 9876543210",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 1234",
    customerAddress: "221B Baker Street, London",
    shipping: "Free",
    status: "Delivered",
    amount: 129.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00002",
    productName: "Bluetooth Speaker",
    customerImg: customerImg2,
    date: "2023-10-02",
    customerName: "Jane Smith",
    customerEmail: "jane@example.com",
    customerPhone: "+91 9123456780",
    paymentMethod: "Paypal",
    customerAddress: "10 Downing St, London",
    shipping: "Express",
    status: "Processing",
    amount: 89.49,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00003",
    productName: "Smart Watch",
    customerImg: customerImg3,
    date: "2023-10-03",
    customerName: "Alice Johnson",
    customerEmail: "alice@example.com",
    customerPhone: "+91 9988776655",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 5678",
    customerAddress: "742 Evergreen Terrace, Springfield",
    shipping: "Standard",
    status: "Cancelled",
    amount: 199.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00004",
    productName: "Gaming Keyboard",
    customerImg: customerImg4,
    date: "2023-10-04",
    customerName: "Bob Marley",
    customerEmail: "bob@example.com",
    customerPhone: "+91 9080706050",
    paymentMethod: "Net Banking",
    customerAddress: "1600 Pennsylvania Ave NW, Washington",
    shipping: "Standard",
    status: "Delivered",
    amount: 79.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00005",
    productName: "LED Monitor",
    customerImg: customerImg5,
    date: "2023-10-05",
    customerName: "Charlie Puth",
    customerEmail: "charlie@example.com",
    customerPhone: "+91 8765432109",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 9876",
    customerAddress: "123 Elm Street, Gotham",
    shipping: "Express",
    status: "Processing",
    amount: 225.75,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00006",
    productName: "HD Webcam",
    customerImg: customerImg6,
    date: "2023-10-06",
    customerName: "Daniel Craig",
    customerEmail: "daniel@example.com",
    customerPhone: "+91 9988223344",
    paymentMethod: "Paypal",
    customerAddress: "456 Pine Street, Metropolis",
    shipping: "Free",
    status: "Cancelled",
    amount: 55.0,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00007",
    productName: "External SSD",
    customerImg: customerImg1,
    date: "2023-10-07",
    customerName: "Eve Torres",
    customerEmail: "eve@example.com",
    customerPhone: "+91 9012345678",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 4321",
    customerAddress: "500 Sunset Blvd, Los Angeles",
    shipping: "Standard",
    status: "Delivered",
    amount: 145.5,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00008",
    productName: "Noise Cancelling Headphones",
    customerImg: customerImg2,
    date: "2023-10-08",
    customerName: "Frank Castle",
    customerEmail: "frank@example.com",
    customerPhone: "+91 9345678901",
    paymentMethod: "Net Banking",
    customerAddress: "700 Ocean Drive, Miami",
    shipping: "Standard",
    status: "Processing",
    amount: 199.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00009",
    productName: "VR Headset",
    customerImg: customerImg3,
    date: "2023-10-09",
    customerName: "Grace Hopper",
    customerEmail: "grace@example.com",
    customerPhone: "+91 9678901234",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 1122",
    customerAddress: "9 Silicon Valley, California",
    shipping: "Express",
    status: "Cancelled",
    amount: 349.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00010",
    productName: "Mechanical Keyboard",
    customerImg: customerImg4,
    date: "2023-10-10",
    customerName: "Harry Styles",
    customerEmail: "harry@example.com",
    customerPhone: "+91 9456123789",
    paymentMethod: "Paypal",
    customerAddress: "111 King St, Toronto",
    shipping: "Free",
    status: "Processing",
    amount: 89.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00011",
    productName: "Laptop Stand",
    customerImg: customerImg5,
    date: "2023-10-11",
    customerName: "Isla Fisher",
    customerEmail: "isla@example.com",
    customerPhone: "+91 9345612789",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 2468",
    customerAddress: "221 Rainbow Road, Wonderland",
    shipping: "Standard",
    status: "Delivered",
    amount: 49.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00012",
    productName: "Portable Charger",
    customerImg: customerImg6,
    date: "2023-10-12",
    customerName: "Jake Peralta",
    customerEmail: "jake@example.com",
    customerPhone: "+91 9234567810",
    paymentMethod: "Paypal",
    customerAddress: "99 Brooklyn, NY",
    shipping: "Free",
    status: "Cancelled",
    amount: 25.49,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00013",
    productName: "USB-C Hub",
    customerImg: customerImg1,
    date: "2023-10-13",
    customerName: "Kevin Hart",
    customerEmail: "kevin@example.com",
    customerPhone: "+91 9011122233",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 3344",
    customerAddress: "404 Maple Ave, Chicago",
    shipping: "Standard",
    status: "Delivered",
    amount: 39.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00014",
    productName: "Desk Lamp",
    customerImg: customerImg2,
    date: "2023-10-14",
    customerName: "Laura Palmer",
    customerEmail: "laura@example.com",
    customerPhone: "+91 8123456790",
    paymentMethod: "Paypal",
    customerAddress: "234 Valley Rd, Twin Peaks",
    shipping: "Free",
    status: "Processing",
    amount: 29.5,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00015",
    productName: "Wi-Fi Router",
    customerImg: customerImg3,
    date: "2023-10-15",
    customerName: "Michael Scott",
    customerEmail: "michael@example.com",
    customerPhone: "+91 7766554433",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 5566",
    customerAddress: "1725 Slough Ave, Scranton",
    shipping: "Express",
    status: "Cancelled",
    amount: 99.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00016",
    productName: "Smartphone Tripod",
    customerImg: customerImg4,
    date: "2023-10-16",
    customerName: "Nancy Drew",
    customerEmail: "nancy@example.com",
    customerPhone: "+91 8091234567",
    paymentMethod: "Net Banking",
    customerAddress: "88 Baker St, UK",
    shipping: "Standard",
    status: "Processing",
    amount: 34.75,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00017",
    productName: "Smart Plug",
    customerImg: customerImg5,
    date: "2023-10-17",
    customerName: "Oscar Wilde",
    customerEmail: "oscar@example.com",
    customerPhone: "+91 8000123456",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 7788",
    customerAddress: "321 Lakeview Blvd, Dublin",
    shipping: "Free",
    status: "Delivered",
    amount: 44.44,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00018",
    productName: "Laptop Cooling Pad",
    customerImg: customerImg6,
    date: "2023-10-18",
    customerName: "Pam Beesly",
    customerEmail: "pam@example.com",
    customerPhone: "+91 8899776655",
    paymentMethod: "Paypal",
    customerAddress: "302 Paper Mill Rd, Scranton",
    shipping: "Free",
    status: "Processing",
    amount: 22.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00019",
    productName: "Streaming Microphone",
    customerImg: customerImg1,
    date: "2023-10-19",
    customerName: "Quentin Blake",
    customerEmail: "quentin@example.com",
    customerPhone: "+91 9988007766",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 4455",
    customerAddress: "89 Art Lane, London",
    shipping: "Express",
    status: "Cancelled",
    amount: 134.95,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00020",
    productName: "Ring Light",
    customerImg: customerImg2,
    date: "2023-10-20",
    customerName: "Rachel Green",
    customerEmail: "rachel@example.com",
    customerPhone: "+91 9321456789",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 6677",
    customerAddress: "12 Central Perk St, NYC",
    shipping: "Standard",
    status: "Delivered",
    amount: 49.0,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00021",
    productName: "Graphic Tablet",
    customerImg: customerImg3,
    date: "2023-10-21",
    customerName: "Steve Jobs",
    customerEmail: "steve@example.com",
    customerPhone: "+91 9111223344",
    paymentMethod: "Net Banking",
    customerAddress: "1 Apple Park Way, Cupertino",
    shipping: "Express",
    status: "Processing",
    amount: 359.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00022",
    productName: "Smart LED Strip",
    customerImg: customerImg4,
    date: "2023-10-22",
    customerName: "Tony Stark",
    customerEmail: "tony@example.com",
    customerPhone: "+91 9999888877",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 7788",
    customerAddress: "10880 Malibu Point, California",
    shipping: "Standard",
    status: "Cancelled",
    amount: 67.89,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00023",
    productName: "Wireless Charger",
    customerImg: customerImg5,
    date: "2023-10-23",
    customerName: "Uma Thurman",
    customerEmail: "uma@example.com",
    customerPhone: "+91 9076543210",
    paymentMethod: "Paypal",
    customerAddress: "700 Movie Blvd, Hollywood",
    shipping: "Free",
    status: "Delivered",
    amount: 29.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00024",
    productName: "Bluetooth Mouse",
    customerImg: customerImg6,
    date: "2023-10-24",
    customerName: "Victor Hugo",
    customerEmail: "victor@example.com",
    customerPhone: "+91 7766112233",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 8899",
    customerAddress: "55 Paris Ave, France",
    shipping: "Free",
    status: "Processing",
    amount: 24.5,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00025",
    productName: "Smart Light Bulb",
    customerImg: customerImg1,
    date: "2023-10-25",
    customerName: "Wendy Wilson",
    customerEmail: "wendy@example.com",
    customerPhone: "+91 8000111222",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 3345",
    customerAddress: "41 Sunshine Rd, Sydney",
    shipping: "Standard",
    status: "Cancelled",
    amount: 19.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00026",
    productName: "Mini Projector",
    customerImg: customerImg2,
    date: "2023-10-26",
    customerName: "Xander Cage",
    customerEmail: "xander@example.com",
    customerPhone: "+91 9876543211",
    paymentMethod: "Net Banking",
    customerAddress: "300 Mountain Peak, Tibet",
    shipping: "Express",
    status: "Processing",
    amount: 159.9,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00027",
    productName: "Action Camera",
    customerImg: customerImg3,
    date: "2023-10-27",
    customerName: "Yara Greyjoy",
    customerEmail: "yara@example.com",
    customerPhone: "+91 9123009876",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 1230",
    customerAddress: "999 Sea Shore, Iron Islands",
    shipping: "Standard",
    status: "Delivered",
    amount: 209.95,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00028",
    productName: "Noise Isolating Earbuds",
    customerImg: customerImg4,
    date: "2023-10-28",
    customerName: "Zayn Malik",
    customerEmail: "zayn@example.com",
    customerPhone: "+91 9988998877",
    paymentMethod: "Paypal",
    customerAddress: "12 Music Lane, London",
    shipping: "Free",
    status: "Cancelled",
    amount: 79.5,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00029",
    productName: "Stylus Pen",
    customerImg: customerImg5,
    date: "2023-10-29",
    customerName: "Alan Turing",
    customerEmail: "alan@example.com",
    customerPhone: "+91 9112233445",
    paymentMethod: "Debit Card",
    cardNumber: "**** **** **** 4567",
    customerAddress: "456 Computation Dr, Cambridge",
    shipping: "Standard",
    status: "Delivered",
    amount: 33.33,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
  {
    orderId: "ORD-00030",
    productName: "HDMI Cable",
    customerImg: customerImg6,
    date: "2023-10-30",
    customerName: "Bruce Wayne",
    customerEmail: "bruce@example.com",
    customerPhone: "+91 9090909090",
    paymentMethod: "Credit Card",
    cardNumber: "**** **** **** 9999",
    customerAddress: "1007 Mountain Drive, Gotham",
    shipping: "Express",
    status: "Processing",
    amount: 14.99,
    discount: 2.5,
    shippingRate: 5,
    product: [
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 2,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 3,
        productId: "#25421",
      },
      {
        productName: "Noise Isolating Earbuds",
        productImg: DummyPro,
        productPrice: 79.5,
        productQuantity: 1,
        productId: "#25421",
      },
    ],
  },
];
